LX3JL/xlxd

src/makefile

If you "make clean" when no .o files exist it results in an error:
--- 8< ---
user@host:~/dev/xlxd/src$ make clean
rm *.o
user@host:~/dev/xlxd/src$ make clean
rm *.o
rm: cannot remove ‘*.o’: No such file or directory
make: *** [clean] Error 1
--- 8< ---
It may be better to use $(RM) (which results in "rm -f" acutally) that does not fail if no .o files exists.

Use predefined $(RM)

---

dashboard2/index.php
dashboard2/pgs/users.php

This is the fix to the issue #7.
I also fixed the heading text that was hardcoded for XLX724.

Fix to issue #7

---

dashboard/pgs/peers.php

If the IP addresses on the peers page are not hidden they contain a hyper link. This link is not pointing to the dashboard in every case. For XLX518 for example the dashboard is reachable via a sub domain. 
So instead of pointing to the IP address it is more helpful to get the dashboard URL from the XLX API server. This patch is intended to do this.

Link to Peers dashboards instead of base IP address

---

src/cdcsprotocol.cpp

As every DCS data packet has both the D-STAR header info and DV data in it,
we must process DV data for all DCS data packets, including the first packet
of a stream.

Fix missing first frame from outgoing DCS stream

---

src/cclients.cpp
src/cdextraclient.h
src/cdplusclient.h
src/cpeers.cpp

I replaces GetProtocol with GetProtocolName in order to find the protocol name in the logs instead of just the plain number. I also renamed "Dplus" to "DPlus" and "Dextra" to "DExtra" in order to comply with what is commonly used.

Use protocol names instead of numbers in logs

---

.gitignore
ambedtest/makefile

The FT2xx headers are not used in the code. So they should not be linked to by the makefile.

FT2xx driver is not needed for ambedtest

---

README.md
src/makefile

make clean does not remove the built binary. That can cause confusion in cases where the build process fails. In such case the binary is still there and one could use that by mistake.
I suppose "make clean" should also remove the binary from previous builds to make sure the newly built one is really new.

Make "make clean" also remove the binary

---

src/cdmriddir.cpp

The current implementation of the API function to pull DMR IDs does not work. 
There is a double slash betweens hostname and path (not really a problem I guess) and
there are some carriage returns (CR aka. 0x0d) missing to separate lines in the HTTP protocol.
The latter results in an error message being generated by the API server.

Remove double slash and add some carriage returns

---

ambed/makefile
ambed/readme
ambedtest/makefile
src/makefile

Change makefile of ambed according to https://github.com/phl0/xlxd/commit/8a545b99c810d8be1b09eb237a2c6d404e4f76ef for xlxd.
Also made the makefiles a little more portable with use of variables for $(EXECUTABLE)

Add ambed binary to make clean

---

src/cdmrmmdvmprotocol.cpp
src/cdmrmmdvmprotocol.h
src/cdmrplusprotocol.cpp
src/cdmrplusprotocol.h

When there's a client or user connection attempt with invalid DMR ID, currently we can see the invalid DMR ID below:
Aug 30 09:26:48 XLX xlxd: DMRmmdvm connect packet from unrecognized id 466112
Aug 30 09:26:48 XLX xlxd: DMRmmdvm packet (8)
Aug 30 09:26:55 XLX xlxd: DMRmmdvm connect packet from unrecognized id 466111
Aug 30 09:26:55 XLX xlxd: DMRmmdvm packet (8)
Aug 30 09:26:58 XLX xlxd: DMRmmdvm connect packet from unrecognized id 466112
Aug 30 09:26:58 XLX xlxd: DMRmmdvm packet (8)
However, I think it might be better to log the source IP of the client/user for security reason:
Aug 30 10:06:56 xlx887 xlxd: DMRmmdvm connect packet from IP address 10.100.1.40 / unrecognized id 466100
Aug 30 10:06:56 xlx887 xlxd: DMRmmdvm packet (8)
Aug 30 10:07:06 xlx887 xlxd: DMRmmdvm connect packet from …

Improve log messages for DMRMmdvm and DMRPlus protocol packets

---

src/cclients.cpp
src/cdextraclient.h
src/cdplusclient.h
src/cpeers.cpp

I have done some changes in https://github.com/LX3JL/xlxd/pull/29 that were merged into master branch with https://github.com/LX3JL/xlxd/commit/76dc7d1ecfc790d6d91a6e7cfc9579f3709c1687.
But these were overwritten with https://github.com/LX3JL/xlxd/commit/83278d13 (reported by @dg0tm).
I guess this was a mistake and would like to have that integrated again.

Redo changes of PR #29 previously overwritten with commit 83278d13

---

dashboard/index.php
dashboard2/index.php

This is a small patch to dashboard and dashboard2 pages to use location.reload() instead of location.href so that browsers keep page scroll position after auto page reloads, because it is very annoying to try to browse page with many users or long activity log and having it always scrolling to top every few seconds...
It inherently fixes bug on Traffic page where "iface" GET var would be lost on every page reloads.
Also fixed missing SuspendPageRefresh() on dashboard2, called to stop auto refresh while user is typing on callsign/module filtering input fields.

dashboard: avoid page scroll to top on reloads

---

dashboard/index.php
dashboard2/index.php

Small addition (to my last pr) to ensure the 'do' GET request are not processed multiple times on reloads... not critical as it is currently only used for 'resetfilter' and it causes no problem with it, however I still think it's better to fix it properly...

don't use location.reload() if there is a 'do' GET request

---

dashboard/pgs/class.reflector.php
dashboard2/pgs/class.reflector.php

Use an array indexed by dxcc prefix for faster lookups instead of scanning whole Flagarray and it's dxcc nested arrays (done lots of times when there are many last heard entries), which is very slow and resource hungry... before this change my server was taking ~360ms to generate users page (with 80 last heard entries), after this small change it takes ~18ms instead.

dashboard performance enhancement

---

src/cdcsprotocol.cpp
src/cdextraprotocol.cpp
src/cdmrmmdvmprotocol.cpp
src/cdmrplusprotocol.cpp
src/cdplusprotocol.cpp
src/cprotocol.cpp
src/cprotocol.h
src/cxlxprotocol.cpp
src/cxlxprotocol.h

The OnDvLastFramePacketIn() function closed the current stream before
HandleQueue() was called, so the stream's client lost it's stream master status
and HandleQueue() sent the client's last (stream closing) frame back to the
sender.
Applying this commit closes the stream only after HandleQueue() has been
called so no unnecessary call end frame reflection happens to the transmitting
client.

Prevent sending stream close frames back to the sender

---

src/cwiresxcmdhandler.cpp

Fix for #159 
Tested on FT-70DR and the word MODULE now displays rather than M and blank spaces.

YSF module display fix for U/C only radios such as FT-70DR

---

src/cprotocol.cpp

This deletes Packet Frames that can't be found in a Stream by their StreamID. This plugs a memory leak.

Fix orphaned Frame memory leak

---

src/crawsocket.cpp

Maximum size of ICMP packet is 64k while buffer allocation was UDP_BUFFER_LENMAX, while read was up to 64k.
This will cause a crash on read in the subsequent read for packets with length greater than UDP_BUFFER_LENMAX via a buffer overflow.

Update buffer allocation to the correct size

---

src/ccodecstream.cpp
src/ctranscoder.cpp
src/cudpsocket.cpp
src/cudpsocket.h

Hi,
The public reflector IP is used as source IP for communication with the transcoder. This causes some issues on some systems with peeky firewalls.
This aims to solve this.
By using 0.0.0.0 when opening the socket the "best" address will be used to reach the transcoder.
73
Geoffrey F4FXL / KC3FRA

Avoid using public IP for transcoder connection

---

src/cdplusprotocol.cpp

This patch fixes dplus sending header packets at wrong frequency, depending on the number of dplus clients connected on the reflector, as m_iSeqCounter was being wrongly incremented for each client that each dv packet is sent and not just per-packet, in some cases (for eg. with 3 or 7 clients connected) only one client could actually get lots of header packets and the other clients get none.

fix dplus sending header packets inconsistently

---

src/cdextraprotocol.cpp
src/cdextraprotocol.h

This patch adds code to cache header packets on dextra protocol code (similarly to how it is already done for dplus and dcs) and when new dextra clients connect to the reflector, if there is any other client already streaming on the module, send a copy of the cached header packet to the connecting client (right after Ack), so it can properly listen the already streaming client.

allow connecting dextra clients to listen already streaming clients

---

dashboard/index.php
dashboard/pgs/config.inc.php
dashboard/pgs/modules.php

This patch adds a new page on dashboard to list all modules with its names from config.inc.php (helpful to know module names even for modules with no users connected) and eventually useful info for users on how to link them.

Add "Modules list" page

---

src/creflector.cpp

Prevent segfault when WireGuard is active and an interface has `ifaptr->ifa_addr == NULL`

fix Linux AF_INET iteration segfault

---

src/ccallsign.cpp
src/main.h

Small patch to change SetYsfCallsign() to trim/stop parsing callsign when it finds null char, this was actually done before v2.5.x as callsign was copied until strlen() on constructor function. This workarounds DVSwitch YSF users being unable to TX on v2.5.x as described on this topic: https://xlxbbs.epf.lu/viewtopic.php?p=2227#p2227

change SetYsfCallsign() to trim callsign on null char

---

dashboard/pgs/functions.php
dashboard2/pgs/functions.php

N0AD asked me for help with a strange issue he was experiencing on his XLX720 with dashboard intermittently (on refreshes) showing repeated callsigns (i.e showing the same callsign for every/most node connected) on his server, conclusion:
_"After looking at code I think I understand now how it happens, actually I'm surprised why it doesn't happen on my/other servers... if my suspect is correct the problem must be timing triggered. When generating internal random ids for nodes, random generator is being initialized for each node (bad idea) using microtime() value as seed, and... probably your server is either very fast or hardware system timer is low resolution, or code is much optimized on that php version... something is probably causing random generator to be initialized on your server …

fix dashboard intermittently showing repeated callsigns on some servers

---

src/csemaphore.cpp
src/csemaphore.h
src/ctranscoder.cpp

This patch fixes an old bug on xlxd related with ambed openstream timeout, actually if the openstream response packet from ambed to xlxd is completely lost then no problem happens at all, however if timeout is reached but xlxd still gets the packet after timeout then transcoding gets fully broken with crashing streams forever until xlxd is restarted.
The problem is discussed at issues https://github.com/LX3JL/xlxd/issues/115 , https://github.com/LX3JL/xlxd/issues/141 and probably also https://github.com/LX3JL/xlxd/issues/168 , the workaround of @lucamarche-iz1mlt is to tweak this timeout (and inherently some other timeouts) to an high value to avoid it but the bug is still there... also it should be easy for a malicious user to take advantage of this to break any XLX, as easy as simulate …

fix ambed openstream timeout issue

---

src/cpacket.cpp
src/cpacketstream.cpp

This small patch fixes frame sequence applied by UpdatePids() (i.e. for streams initiated on different mode), m_uiPacketCntr should not be incremented by dv header packet else sequence for dv frames will start at 1 instead of 0 as it should.
This caused even further issues for DMR/YSF: with m_uiDmrPacketSubid and m_uiYsfPacketSubId also being calculated from the above, actually if we have for example a stream initiated on D-Star, 1st and 2nd dv frames would be transcoded to 2nd and 3rd AMBE frames of the DMR "triplet", the 1st AMBE frame would be the one stored at m_StreamsCache from the previous stream! and... frame sequence on EncodeDvPacket() being picked from that DvFrame0 (the one from previous stream), then something random...
The wrong frame sequence caused all DMR streams (when …

fix frame sequence for streams initiated on different mode

---

ambed/cusb3xxxinterface.cpp
ambed/cusb3xxxinterface.h

This patch improves ambed to be able to handle and recover from device communication errors/timeouts.
Before this patch, when ambed failed to get reply from a device for some packet (1 or 2 depending of device fifo size...) then such device would not be usable anymore until restarting ambed (because ​m_iSpeechFifolLevel or m_iChannelFifolLevel vars would never decrement), the patch implements a timeout to restart these and a check to verify if the device is unresponsive, if yes then close and reopen/reinitialize the device. These problems are very frequent on some systems like Raspberry Pi requiring ambed to be restarted from time to time.
I did also include code to drop lagged packets on device queue after channel is closed, these lagged packets can accumulate if device have performance …

make ambed more robust to handle device errors

---

ambed/cusb3xxxinterface.cpp

This patch fixes an occasional/random ambed crash (showing "Illegal instruction" error) that happens sometimes when some device interface fails Init(), when such happens interface instance is destroyed, for example at: https://github.com/LX3JL/xlxd/blob/adec5c8d14855136c702780723af4263d51edfe9/ambed/cftdidevicedescr.cpp#L397 and the issue is that queues are destroyed on CUsb3xxxInterface destructor while thread still running (thread is only stopped on destructor of parent class CVocodecInterface, last thing to happen), then the crash seems caused by eventual accesses to destroyed queues from that still running thread... solution is to stop thread first...

fix occasional ambed crash when device fails init

---

src/cdmriddir.h

`CDmridDir` is a base class for `CDmridDirHttp` and `CDmridDirFile`, so its destructor should be marked virtual to prevent undefined behavior. This problem is not currently exposed because the program uses `#ifdef` semantics to create direct instantiations of derived classes in `main.h`:
```c
#if (DMRIDDB_USE_RLX_SERVER == 1)
class CDmridDirHttp;
extern CDmridDirHttp   g_DmridDir;
#else
class CDmridDirFile;
extern CDmridDirFile   g_DmridDir;
#endif
```

CDmridDir destructor should be virtual

---

src/cdmriddir.cpp

POSIX states that the return value of `isdigit()`: 
> shall return non-zero if c is a decimal digit; otherwise, they shall return 0.
Thus the form:
`ok &= isdigit(x)`
is invalid since the runtime is not required to return 1.
This bug was observed on Debian 11 while using the clang toolchain. In that environment, `isdigit()` returns 2048 for a positive match.

isdigit() may return any non-zero result for success

---

src/cg3protocol.cpp
src/cg3protocol.h

During testing in a sandbox environment, xlxd crashed in `CG3Protocol::Close()`. The root cause was dereferencing `m_pPresenceThread` when the object had never been initialized. In this case an error occured during `::Init()` which set `ok=false`, so the initialization of the threads was skipped.
This commit also resolves an issue where all 3 worker threads were being assigned to `m_pPresenceThread` during `std::thread` creation.
This commit does 5 things:
(1) Default initializes the thread pointers to avoid the crash.
(2) Fixes an issue where all three worker threads were initialized to the same variable.
(3) Wraps the thread allocation with `try`/`catch` since `std::thread` can throw.
(4) Does some light cleaning in `::Close`, e.g., converting `NULL` to `nullptr`.
(5) Resolves a …

cg3protocol: fix crash/default initialize std::thread pointers

---

src/cysfprotocol.cpp

I can't find real documentation about YSF protocol, however I did look at G4KLX code, like MMDVMHost, and I see he always set and rely on this bit to identify EOT:
https://github.com/g4klx/MMDVMHost/blob/f02cbcb141e53f1aeac5d0b6ee6dfc9d3b6e2b61/YSFControl.cpp#L915
MMDVMHost RX from XLX without the patch:
```
M: 2023-12-08 03:08:42.585 YSF, received network data from CT2HRB to DG-ID 0 at CT2HRB
M: 2023-12-08 03:08:45.345 YSF, network watchdog has expired, 1.4 seconds, 0% packet loss, BER: 0.0%
M: 2023-12-08 03:08:47.312 YSF, received network data from CT2HRB to DG-ID 0 at CT2HRB
M: 2023-12-08 03:08:50.628 YSF, network watchdog has expired, 1.9 seconds, 0% packet loss, BER: 0.0%
```
MMDVMHost RX from XLX after the patch:
```
M: 2023-12-08 03:30:18.097 YSF, received network data from CT2HRB …
```

set eot status bit for ysf last packet

---

src/cdmrmmdvmprotocol.cpp
src/cdmrmmdvmprotocol.h

This patch implements sending embedded LC data on voice bursts for DMRmmdvm, this allows late entry and improves compatibility with some clients (like BlueDV+DVMega and Peanut linking using DMRmmdvm protocol).

add embedded LC data for DMRmmdvm

---

src/cxlxprotocol.cpp

In the original code when no transcoder connected (i.e. xlxd not connected to ambed) streams to xlx peers downgrade to using rev1 xlx protocol dv packets (dstar only ambe, no dmr/ysf) despite connected to rev2 peer... then dmr/ysf voice only really pass through xlx peers (incl. BM) when transcoder is connected. I see no reason and no sense for this downgrade when no transcoder connected, as reflector may be used for just dmr/ysf and these should obviously pass to peers!? After this patch it will always use rev2 packets on interlinks to rev2 peers (rev1 packets will still be used to rev1 peers).
Problem discussed at: https://xlxbbs.epf.lu/viewtopic.php?p=2871

allow pass dmr/ysf to peers, without transcoding
